version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: log-db
    ports:
      - 5432:5432
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres -d log-db"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - postgres:/var/lib/postgresql/data
  api_backend:
    container_name: exchange_rates_backend
    image: exchange_rates_backend
    build:
      context: .
    ports:
      - 8082:8082
    depends_on:
      db:
        condition: service_healthy
    environment:
      # APPLICATION PROPERTIES
      - SERVER_PORT=8082
      # DATABASE
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      # POSTGRESQL
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/log-db
      # JPA
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
volumes:
  postgres: